### ISSUE TITLE
Format uuid is invalid

### ISSUE THREAD

**Issue by BiteBit** [DScheglov/mongoose-schema-jsonschema#1]
Hi, i'm using your module as depends. I validate the schema by [ajv](https://github.com/epoberezkin/ajv), but the result is invalid.
ObjectId is not a uuid, so the format uuid make it validate failed.
Thank you.

**Comment by DScheglov** [comment]
"format" field was removed from ObjectId json schema.
Please update mongoose-schema-jsonschema.

Thank you for an issue :)

**Comment by BiteBit** [comment]
Thanks for quick reply and help.
