### ISSUE TITLE
exclude

### ISSUE THREAD

**Issue by sarkistlt** [DScheglov/mongoose-schema-jsonschema#10]
thanks for module, saved my time! one question, is it possible to exclude some fields? would be really useful if we'll be able to exclude some certain fields like ids, pw, keys etc. thanks!

**Comment by DScheglov** [comment]
Hi, @sarkistlt 

Exclude works for model.jsonSchema, please consider the appropriate test-suite
https://github.com/DScheglov/mongoose-schema-jsonschema/blob/master/test/suites/selection.js

**Comment by sarkistlt** [comment]
I see, thanks!
