### ISSUE TITLE
Populate and fields

### ISSUE THREAD

**Issue by jumper85** [DScheglov/mongoose-schema-jsonschema#11]
Hi, I use this package to make development of an API using typescript, typegoose and other packages as simple as possbile. 

During my developments I stumbled over a small problem with schema creation, referenced models and field exclusion. After some debugging, I identified the problem in this function:

```javascript
function model_jsonSchema(fields, populate, readonly) {
  var jsonSchema = this.schema.jsonSchema(this.modelName);

  __excludedPaths(this.schema, fields).forEach(
    __delPath.bind(null, jsonSchema)
  );

  if (populate != null) {
    jsonSchema = __populate.call(this, jsonSchema, populate);
  };

  if (readonly) {
    __excludedReadonlyPaths(jsonSchema, readonly);
  }

  if (fields) __removeRequired(jsonSchema);

  return jsonSchema;
};
```

Do you think it is possible to switch logic for populate and excludes like this:

```javascript
function model_jsonSchema(fields, populate, readonly) {
  var jsonSchema = this.schema.jsonSchema(this.modelName);

  if (populate != null) {
    jsonSchema = __populate.call(this, jsonSchema, populate);
  };

  __excludedPaths(this.schema, fields).forEach(
    __delPath.bind(null, jsonSchema)
  );

  if (readonly) {
    __excludedReadonlyPaths(jsonSchema, readonly);
  }

  if (fields) __removeRequired(jsonSchema);

  return jsonSchema;
};
```

With this order population happens first and after that exclusions can be done on subdocuments like this, which is an example from my code:

```javascript
const pageSchema = require("../classes/models/server/Page")
        .jsonSchema(
            "-__v -author.password -author.__v -modifiedBy.password -modifiedBy.__v -category.__v",
            "author modifiedBy category",
        );
```

author, modifiedBy and category are referenced schemas which are populated and after that I remove some properties.

If you have any questions, feel free to ask.

**Comment by DScheglov** [comment]
Hi, @jumper85 , sorry for late answer.
I will check your proposition. If it doesn't breaks the tests I will change code accordingly.

Thank you.

**Comment by jloveridge** [comment]
Any status update on making this update?

**Comment by DScheglov** [comment]
Hi, sorry for latency ...

Updates for you in relese 1.2.0:
https://github.com/DScheglov/mongoose-schema-jsonschema/releases/tag/v1.2.0
