### ISSUE TITLE
String minlength and maxlength don't work

### ISSUE THREAD

**Issue by kalvinarts** [DScheglov/mongoose-schema-jsonschema#21]
The **String** type needs `minlength` and `maxlength` options to be in lowercase as specified in the **mongoose** docs:

[SchemaStringOptions.prototype.maxlength](https://mongoosejs.com/docs/api.html#schemastringoptions_SchemaStringOptions-maxlength)
[SchemaStringOptions.prototype.minlength
](https://mongoosejs.com/docs/api.html#schemastringoptions_SchemaStringOptions-minlength)
PR #20

**Comment by DScheglov** [comment]
Fixed in [v1.3.1](https://github.com/DScheglov/mongoose-schema-jsonschema/releases/tag/v1.3.1)
