### ISSUE TITLE
1.4.0 - Error: Cannot find module '../config'

### ISSUE THREAD

**Issue by manikumarrepuri** [DScheglov/mongoose-schema-jsonschema#22]
Everything was fine with the earlier version, but suddenly my tests started failing then had a look at the version and it's 1.4.0 now. 
Verified downgrading the version and my tests passed. 

Throwing error "Cannot find module '../config'.

**Comment by srinivasrk** [comment]
I can see that in `schema.js` file inside lib you are require `../config` but config in not in the previous directory. It should be `./config` I can create a PR to fix this.

**Comment by DScheglov** [comment]
Fixed in v1.4.1.

Thanks for fast issue

**Comment by manikumarrepuri** [comment]
Thanks for the swiftly fix. Excellent.
