### ISSUE TITLE
Description for mixed

### ISSUE THREAD

**Issue by jawadst** [DScheglov/mongoose-schema-jsonschema#3]
The description field is not picked up for mongoose.Schema.Types.Mixed properties.

The description is actually pretty useful in these cases as these properties can get pretty complex.

**Comment by DScheglov** [comment]
Hi, thank you. Taking to work.
Could you give me the sample. I will inlucde it in the test suites

**Comment by DScheglov** [comment]
Bug fixed.
see test-suite: https://github.com/DScheglov/mongoose-schema-jsonschema/blob/master/test/suites/description.js

**Comment by jawadst** [comment]
Thanks for the quick fix!
