### ISSUE TITLE
Support mongoose 6.0.2

### ISSUE THREAD

**Issue by TheRav3n** [DScheglov/mongoose-schema-jsonschema#32]
Mongoose 6.0.2 renames Types.Embedded to Types.Subdocument.

I opened PR #31 to fix the issue, but a more elegant solution would be appreciated, in order to keep support for previous mongoose versions.

Proposal: using  the `npm list`  command to get a list of all installed packages, find mongoose in the output and extract version. Compare major version and if greater than 6, apply fix.

In the meanwhile, please update the package as latest version should be the one supported.

Have a great day!

**Comment by DScheglov** [comment]
Hey, @TheRav3n thanks a lot of pointing the issue.

Version `mongoose-schema-jsonschema` supports `mongoose@6.x` since v2.0.0 (already published).
