### ISSUE TITLE
npm warns mongoose@^5.0.0 required

### ISSUE THREAD

**Issue by bnielsen1965** [DScheglov/mongoose-schema-jsonschema#34]
When using mongoose 6.x.x npm install warns that mongoose-schema-jsonschema requires mongoose@^5.0.0.

Should your package.json dependencies be updated to "mongoose": "^6.0.0", or am I missing something?

**Comment by DScheglov** [comment]
@bnielsen1965 ,
Thank you for issue. 

It has been fixed in the [v2.0.1](https://github.com/DScheglov/mongoose-schema-jsonschema/commit/88dddcd4b7347bf1e16f4069fb055001b5a5fe14)

Fill free to reopen the issue if something on your side goes wrong with that.
