### ISSUE TITLE
Array of Array is not supported

### ISSUE THREAD

**Issue by gilles-yvetot** [DScheglov/mongoose-schema-jsonschema#37]
When generating the json schema, I got the following error:

```
TypeError: Cannot read property 'required' of undefined
    at SchemaArray.array_jsonSchema [as jsonSchema] (/~/Documents/models/node_modules/mongoose-schema-jsonschema/lib/types.js:102:53)
```

It comes from `this.schemaOptions.required`, it looks like `schemaOptions` is not always defined. Especially with the following schema

```javascript
const mongoose = require(`mongoose`)
const VariableSchema = require(`./VariableSchema.js`)

const ElementPathSchema = new mongoose.Schema({
  paths: {
   paths: {
      type: [[VariableSchema]],
      validate: {
        validator: function validateTemplate(arrayOfVariables) {
          return arrayOfVariables.every((variables) =>
            VariableSchema.statics.validateTemplate(variables, `elementQuery`),
          )
        },
        message: `elementPath.paths not valid`,
      },
    }
  },
})
```

**Comment by DScheglov** [comment]
Hey, @gilles-yvetot 
Thank you for registering the issue.
I've fixed it with a quick patch: See v2.0.2.

Feel free to reopen the issue if it doesn't work for you.

**Comment by gilles-yvetot** [comment]
For future reference, here is the [commit](https://github.com/DScheglov/mongoose-schema-jsonschema/commit/9b8ca707b67fccc80ce34678b3ed8c8ebacd2f6f) that fixes this bug

**Comment by DScheglov** [comment]
@gilles-yvetot ,
oh, thank you.

Sorry for not using your PR.
The coveralls reported that coverage was reduced, so ...
And it seems your IDE overrides project linting settings -- your commit contains several linting changes.

**Comment by gilles-yvetot** [comment]
No problem at all, we got a fix and that's what matter.
I was suggesting that you can maybe add an `.editorconfig` , prettier config and eslint config to be more IDE agnostic. I am sure it would help other people bringing PRs in
