### ISSUE TITLE
Description not picked up for array type

### ISSUE THREAD

**Issue by ludetc** [DScheglov/mongoose-schema-jsonschema#4]
Hi, 
It looks like description will not be picked up when type is array, for example:

new mongoose.Schema(
    {
        name: String,
        inputs: {type: [String], index: true, description: "Information operated on by rule"},
        outputs: {description: "Information produced by rule", type: [String]},
    }
);

**Comment by DScheglov** [comment]
Hi, bug reproduced. Taking to fixing. Thank you a lot for your contribution.

**Comment by DScheglov** [comment]
Bug fixed. Please update to + mongoose-schema-jsonschema@1.1.13

**Comment by ludetc** [comment]
Many thanks for the quick fix. Looks like 1.1.13 is not released yet. Will try out when it's ready.

**Comment by DScheglov** [comment]
Oh! Thanks! The version 1.1.13 was released to private npm registry of my company.

Currently updates are published in the public npm.
