### ISSUE TITLE
Usage in NestJS with SchemaFactory.createForClass

### ISSUE THREAD

**Issue by SergioArrighi** [DScheglov/mongoose-schema-jsonschema#40]
Hello,
so I would like to use this library but there is a main point I'm not able to resolve and maybe there is a gap in what I'm trying to achieve.
I have a NestJS application using Mongoose.
Schemas are created as follows:

`
import { PartialType } from '@nestjs/mapped-types';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { ApiProperty } from '@nestjs/swagger';
import { Document } from 'mongoose';

export type CatDocument = Cat & Document;

@Schema()
export class Cat {

  @ApiProperty()
  @Prop()
  name: string;

  @ApiProperty()
  @Prop()
  age: number;

  @ApiProperty()
  @Prop()
  breed: string;
}

export const CatSchema = SchemaFactory.createForClass(Cat)
export class UpdateCat extends PartialType(Cat) {}
`
 
As you can see SchemaFactory.createForClass is invoked to obtain a schema object.
So I thought I could use it with this library but this object doesn't expose the jsonSchema().

When I create as an instance of mongoose Schema then it works.

Is this an incompatibility with NestJS SchemaFactory?

Thanks and best regards

**Comment by SemihY** [comment]
Hi, I faced that issue. This solution may solve your issue.

```
mongoose_schema_jsonschema(mongoose);

const { Schema } = mongoose;

export const CatSchema =  new Schema(SchemaFactory.createForClass(Cat), {});
```
