### ISSUE TITLE
`required` for arrays produce `"minItems": 1`, which is wrong since Mongoose 5

### ISSUE THREAD

**Issue by ulazdins-afs** [DScheglov/mongoose-schema-jsonschema#49]
Currently a schema
```
const BookSchema = new Schema(
  {
    comments: [{
      type: String,
      required: true,
    }]
  },
  schemaOptions,
);
```
generates
```
{
  title: 'Book',
  type: 'object',
  properties: {
    comments: {
      "type": "array",
      "items": {
        "type": "string",
      },
      "minItems": 1
    },
  },
}
```
which is incorrect

From the [docs](https://mongoosejs.com/docs/migrating_to_5.html#array-required):
> In mongoose 5 the required validator only verifies if the value is an array. That is, it will not fail for empty arrays as it would in mongoose 4.

Hence, the expected output would be (no `minItems`):
```
{
  title: 'Book',
  type: 'object',
  properties: {
    comments: {
      "type": "array",
      "items": {
        "type": "string",
      },
    },
  },
}
```

**Comment by DScheglov** [comment]
Fixed in `mongoose-schema-jsonschema@3.0.0`
The major version was increased because the change breaks the existing behavior.
