### ISSUE TITLE
are discriminator supported?

### ISSUE THREAD

**Issue by camille68** [DScheglov/mongoose-schema-jsonschema#7]

**Comment by DScheglov** [comment]
Hi, @camille68, sure discriminators are supported in sense the library generates json-schema for such models wells. However the schema of discriminator is a stand-alone schema meaning it is not an extension of parent schema how it could be expected.

[Test suite](https://github.com/DScheglov/mongoose-schema-jsonschema/blob/e77500e126054f1ead0fb6490c6f0c13171add64/test/suites/discriminators.js) was added to ensure that discriminators are supported.

**Comment by DScheglov** [comment]
The v.1.1.14 will be published at the [registry.npmjs.com](https://www.npmjs.com/package/mongoose-schema-jsonschema) soon (I guess after New Year selebrations will be passed).

**Comment by DScheglov** [comment]
The previous version (v.1.1.13) also generates schema for discriminators but for queries it generates `title`'s of schema like as: `List of <collection-name>` that is the same as for parent model and all others discriminators.

So you could use the v.1.1.13 if you are `ok` with this confusing fact or you could use the library version from github directly:

```shell
npm install git+ssh://git@github.com:DScheglov/mongoose-schema-jsonschema.git#v1.1.14
```

**Comment by DScheglov** [comment]
@markSbrandt, please consider this update

**Comment by DScheglov** [comment]
v1.1.14 has been published at the registry.npmjs.com
