### ISSUE TITLE
mongoose 5.x support

### ISSUE THREAD

**Issue by jupe** [DScheglov/mongoose-schema-jsonschema#8]
Mongoose 5.x is released. When we could get support for it ?

**Comment by jupe** [comment]
seems that this still works without any other modifications: https://github.com/jupe/mongoose-schema-jsonschema/commit/98abbe42f9c5a396020f4e036b29ce5c50aebcd5 .

**Comment by DScheglov** [comment]
Oh! Thank you for notice.
I will update dependencies and travis-ci settings

**Comment by DScheglov** [comment]
@jupe - new releas has been issued:
https://github.com/DScheglov/mongoose-schema-jsonschema/tree/v1.1.15

**Comment by jupe** [comment]
Thanks!
